issuer: https://token.actions.githubusercontent.com
subject: repo:amanstep/maintained-actions-playground:ref:refs/heads/main
claim_pattern:
  workflow_ref: amanstep/maintained-actions-playground/\.github/workflows/octo-sts-action\.yaml@refs/heads/main

permissions:
  contents: read
